class settings:
    NAME = 'TomzzHighCastle(THC)'
    WIDTH=1200 
    HEIGHT=1000
    WID_HEI_str = str(WIDTH)  + 'x' + str(HEIGHT)
    best_case = "[Best Case] "
    average_case = "[Average Case] "
    worst_case = "[Worst Case] "
    mio_euro = " Million Euro"
    cyc = " Cycles"
    tn = " tons"
    ppy = "Profit per Year: "
    tpy = "Turnover per Year: "
    cpy = "Cycles per Year: "
    ypy = "Yield per Year: "
    ypp = "Yield per Plant: "
    words = ["Best Case:","Average Case:", "Worst Case:"]
    price_p_g = 6
    average_cycles = 4
    average_yield = 100
    cost_p_warehouse = 1000000
    number_of_plants = 3000
    number_of_warehouses = 1
    best_case_chance = 1.5
    worst_case_chance = 0.5